name: mario
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.*
  - pip
  - ca-certificates
  - certifi
  - openssl
  - scipy=1.4.1
  - scikit-image=0.17.2
  - pip:
    - matplotlib
    - cloudpickle==1.3.0
    - future==0.18.2
    - gym==0.17.2
    - gym-super-mario-bros==7.3.0
    - nes-py==8.1.1
    - numpy==1.18.4
    - opencv-python==4.2.0.34
    - pillow==7.1.2
    - pyglet==1.5.0
    - torch==1.5.0
    - torchvision==0.6.0
    - tqdm==4.46.0